package com.car.dealer.common;

public enum Model {
    A1, A3, A4, A5, A6, A7, A8, Q2, Q3, Q4, Q5, Q7, Q8,

    SERIES1, SERIES2, SERIES3, SERIES4, SERIES5, SERIES6, SERIES7, SERIES8, X1, X2, X3, X4, X5, X6, X7, Z3, Z4, Z8, I3, I4,

    ACLASS, BCLASS, CCLASS, CLACLASS, CLSCLASS, ECLASS, GCLASS, GLACLASS, GLBCLASS, GLCCLASS, GLECLASS, GLSCLASS,
    MCLASS, RCLASS, SCLASS, SLCLASS, SLCCLASS, SLKCLASS, VCLASS, XCLASS,

    ALHAMBRA, AROSA, CORDOBA, EXEO, IBIZA, INCA, LEON, MALAGA, MARBELLA, MII, TOLEDO, ALTEA, ATECA, TARRACO, ARONA,

    FAVORIT, FELICIA, OCTAVIA, FABIA, SUPERB, ROOMSTER, YETI, RAPID, CITIGO, KODIAQ, KAROQ, SCALA, KAMIQ,

    AVALANCHE, AVEO, BERETTA, BLAZER, BOLT, CAMARO, CAPRICE, CAPTIVA, CAVALIER, COBALT, COLORADO, CORVETTE, CRUZE,
    EQUINOX, EXPRESS, HHR, IMPALA, LUMINA, MALIBU, MONTECARLO, ORLANDO, S10, SILVERADO, SONIC, SPARK, SUBURBAN, TAHOE,
    TRACKER, TRAILBLAZER, TRAVERSE, TRAX, UPLANDER, VENTURE, VOLT,

    ACCENT, ELANTRA, SONATA, SANTAFE, TUCSON, VELOSTER, GENESIS, I10, I20, I30, I40, KONA, PALISADE, CRETA, VENUE, NEXO, IONIQ,

    MUSTANG, GT, RANGER, MAVERICK, F150, SUPERDUTY, TRANSIT, TRANSITCONNECT, ESCAPE, EDGE, BRONCO, BRONCOSPORT, EXPLORER,
    EXPEDITION, FIESTA, FOCUS, MONDEO, SMAX, GALAXY, ECOSPORT, PUMA, KUGA,

    RUNNER, AVALON, CAMRY, CELICA, COROLLA, CRESSIDA, ECHO, FJCRUISER, HIGHLANDER, LANDCRUISER, MATRIX, MR2, MR2SPYDER,
    PASEO, PREVIA, PRIUS, RAV4, SEQUOIA, SIENNA, SOLARA, SUPRA, T100, TACOMA, TERCEL, TUNDRA, VENZA, YARIS,

    AMAROK, ARTEON, ATLAS, BEETLE, BORA, CADDY, CALIFORNIA, CORRADO, CRAFTER, EOS, FOX, GOLF, JETTA, LUPO, PASSAT,
    PHAETON, POLO, SCIROCCO, SHARAN, TCROSS, TROC, TAIGO, TIGUAN, TOUAREG, TOURAN, VENTO,

    ADAM, AGILA, AMPERA, AMPERAE, ANTARA, ASTRA, CALIBRA, CASCADA, COMBO, CORSA, CROSSLANDX, FRONTERA, GRANDLANDX,
    INSIGNIA, KADETT, KARL, MANTA, MERIVA, MOKKA, MONZA, MOVANO, OMEGA, SENATOR,
    SIGNUM, SINTRA, SPEEDSTER, TIGRA, VECTRA, VIVARO, ZAFIRA,
}
